name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  assign_pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author

  assign_issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    steps:
      - name: Assign issue author
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_SECRET_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;
            const assignee = context.payload.issue.user.login;
            await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              assignees: [assignee]
            });
