name: Auto Merge Changeset Release

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'changeset-release/example' && github.event.review.state == 'approved'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge pull request
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --merge --admin

      - name: Cleanup
        run: rm -rf $GITHUB_EVENT_PATH

    env:
      GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
