name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]
  issues:
    types: [opened]

jobs:
  check_label_and_act:
    runs-on: ubuntu-latest

    steps:
      - name: Check for specific label on PR
        if: github.event_name == 'pull_request'
        id: check_label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_SECRET_TOKEN }}
          script: |
            const labelToCheck = 'your-label-name'; // 확인할 라벨 이름
            const labels = context.payload.pull_request.labels;
            const hasLabel = labels.some(label => label.name === labelToCheck);
            return { hasLabel: hasLabel.toString() }; // 문자열로 반환

      - name: Comment if label is missing
        if: steps.check_label.outputs.hasLabel == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_SECRET_TOKEN }}
          script: |
            const labelToCheck = 'your-label-name';
            const issueOrPr = 'pull request';
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `This ${issueOrPr} does not have the required label. Please add the label '${labelToCheck}' to proceed.`
            });
